export interface ApiEnvelope<T> { data: T; meta?: Record<string, unknown>; errors?: unknown }
export type ApiResult<T> = { ok: true; data: T; source: "api" | "demo" } | { ok: false; message: string; status?: number };
export interface TokenPair { accessToken: string; refreshToken: string; expiresInSeconds: number }
const API_URL = process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/, "");
export const MOCK_MODE = process.env.NEXT_PUBLIC_MOCK_MODE === "true";
const ACCESS_KEY = "dormitory.accessToken", REFRESH_KEY = "dormitory.refreshToken";
function storage(): Storage | null { return typeof window === "undefined" ? null : window.sessionStorage; }
export function getAccessToken(): string | null { return storage()?.getItem(ACCESS_KEY) ?? null; }
export function hasSession(): boolean { return MOCK_MODE || Boolean(getAccessToken()); }
export function saveSession(tokens: TokenPair): void { storage()?.setItem(ACCESS_KEY, tokens.accessToken); storage()?.setItem(REFRESH_KEY, tokens.refreshToken); document.cookie = "dormitory_session=1; Path=/; SameSite=Lax"; }
export function clearSession(): void { storage()?.removeItem(ACCESS_KEY); storage()?.removeItem(REFRESH_KEY); if (typeof document !== "undefined") document.cookie = "dormitory_session=; Path=/; Max-Age=0; SameSite=Lax"; }
function errorMessage(payload: unknown, status: number): string { if (payload && typeof payload === "object") { const value = payload as { message?: string; errors?: { message?: string } | string }; if (value.message) return value.message; if (typeof value.errors === "string") return value.errors; if (value.errors && typeof value.errors === "object" && value.errors.message) return value.errors.message; } return status === 401 ? "เซสชันหมดอายุ กรุณาเข้าสู่ระบบใหม่" : `ดำเนินการไม่สำเร็จ (${status})`; }
async function refreshAccessToken(): Promise<string | null> { const refreshToken = storage()?.getItem(REFRESH_KEY); if (!API_URL || !refreshToken) return null; const response = await fetch(`${API_URL}/auth/refresh`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({refreshToken}) }); if (!response.ok) { clearSession(); return null; } const envelope = await response.json() as ApiEnvelope<TokenPair>; saveSession(envelope.data); return envelope.data.accessToken; }
async function requestApi<T>(path:string, init:RequestInit={}, retry=true):Promise<ApiResult<T>> { if (!API_URL) return {ok:false,message:"ยังไม่ได้ตั้งค่า NEXT_PUBLIC_API_URL"}; const token=getAccessToken(); try { const response=await fetch(`${API_URL}${path}`,{...init,headers:{Accept:"application/json",...(init.body?{"Content-Type":"application/json"}:{}),...(token?{Authorization:`Bearer ${token}`}:{}) ,...init.headers}}); if(response.status===401&&retry){const renewed=await refreshAccessToken();if(renewed)return requestApi<T>(path,init,false)} const payload=response.status===204?null:await response.json().catch(()=>null); if(!response.ok)return {ok:false,status:response.status,message:errorMessage(payload,response.status)}; return {ok:true,data:(payload as ApiEnvelope<T>)?.data as T,source:"api"}; } catch { return {ok:false,message:"เชื่อมต่อ API ไม่ได้ ตรวจสอบว่าเซิร์ฟเวอร์เปิดอยู่และตั้งค่า URL ถูกต้อง"}; } }
export async function apiGet<T>(path:string,fallback:T):Promise<ApiResult<T>> { if(MOCK_MODE)return {ok:true,data:fallback,source:"demo"}; return requestApi<T>(path); }
export async function apiMutation<T>(path:string,body:unknown,method:"POST"|"PATCH"|"PUT"|"DELETE"="POST"):Promise<ApiResult<T>> { if(MOCK_MODE)return {ok:true,data:body as T,source:"demo"}; return requestApi<T>(path,{method,body:method === "DELETE" ? undefined : JSON.stringify(body)}); }
export async function login(email:string,password:string,storeSlug:string):Promise<ApiResult<TokenPair>> { if(MOCK_MODE){const demo={accessToken:"demo-access",refreshToken:"demo-refresh",expiresInSeconds:900};saveSession(demo);return {ok:true,data:demo,source:"demo"}} const result=await requestApi<TokenPair>("/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password,storeSlug})},false);if(result.ok)saveSession(result.data);return result; }
