"use client";
import { useEffect, useState } from "react";
import { PageHead } from "@/components/page-head";
import { Status } from "@/components/status";
import { ApiNotice } from "@/components/api-notice";
import { useApiQuery } from "@/lib/use-api";
import { apiMutation } from "@/lib/api";
import type { BranchDto, RoleDto, UserDto } from "@/lib/api-types";

const emptyUsers: UserDto[] = []; const emptyRoles: RoleDto[] = []; const emptyBranches: BranchDto[] = [];

export default function Users() {
  const users = useApiQuery<UserDto[]>("/users", emptyUsers); const roles = useApiQuery<RoleDto[]>("/roles", emptyRoles); const branches = useApiQuery<BranchDto[]>("/branches", emptyBranches);
  const [items, setItems] = useState<UserDto[]>([]); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [done, setDone] = useState(false);
  useEffect(() => setItems(users.data), [users.data]);
  async function invite(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); const form = new FormData(event.currentTarget); const role = roles.data.find((item) => item.id === String(form.get("roleId"))); const result = await apiMutation<UserDto>("/users", { displayName: String(form.get("displayName")), email: String(form.get("email")), password: String(form.get("password")), roleId: String(form.get("roleId")), allBranches: true, branchIds: [] }); setBusy(false); if (!result.ok) { setError(result.message); return; } const created = { ...result.data, role: role || { id: String(form.get("roleId")), name: "ผู้ใช้งาน" }, branches: [], allBranches: true, status: "ACTIVE" } as UserDto; setItems((current) => [...current, created]); setDone(true); window.setTimeout(() => { setDone(false); setOpen(false); }, 900); }
  return <><PageHead title="ผู้ใช้งาน" subtitle="สร้างบัญชี เลือกบทบาท และจำกัดสาขาที่เข้าถึง" /><ApiNotice loading={users.loading || roles.loading || branches.loading} error={users.error || roles.error || branches.error || error} />
    <div className="page-head-actions"><button type="button" className="button" onClick={() => setOpen(true)}>＋ เชิญผู้ใช้งาน</button></div>
    {open && <div className="modal-backdrop" onMouseDown={() => !busy && setOpen(false)}><section className="modal" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">เพิ่มสมาชิกทีม</div><h2>เชิญผู้ใช้งาน</h2></div><button type="button" className="icon-button" onClick={() => setOpen(false)} disabled={busy}>×</button></div>{done ? <div className="success-state">สร้างผู้ใช้งานเรียบร้อยแล้ว</div> : <form onSubmit={invite}><label className="field"><span>ชื่อที่แสดง</span><input name="displayName" required disabled={busy} /></label><label className="field"><span>อีเมล</span><input name="email" type="email" required disabled={busy} /></label><label className="field"><span>รหัสผ่านเริ่มต้น</span><input name="password" type="password" minLength={8} required disabled={busy} /></label><label className="field"><span>บทบาท</span><select name="roleId" required disabled={busy}>{roles.data.map((role) => <option value={role.id} key={role.id}>{role.name}</option>)}</select></label><div className="modal-actions"><button type="button" className="button ghost" onClick={() => setOpen(false)} disabled={busy}>ยกเลิก</button><button className="button" disabled={busy}>{busy ? "กำลังสร้าง…" : "สร้างผู้ใช้งาน"}</button></div></form>}</section></div>}
    <div className="table-wrap"><table className="data-table"><thead><tr><th>ชื่อ</th><th>อีเมล</th><th>บทบาท</th><th>เข้าถึงสาขา</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>{items.map((u) => <tr key={u.id}><td><strong>{u.displayName}</strong></td><td>{u.email}</td><td>{u.role.name}</td><td>{u.allBranches ? "ทุกสาขา" : u.branches.map((b) => b.branch.name).join(", ") || "—"}</td><td><Status>{u.status === "ACTIVE" ? "ใช้งาน" : "ปิดใช้งาน"}</Status></td><td><button type="button" className="button secondary" onClick={() => window.alert("ฟังก์ชันแก้ไขผู้ใช้งานจะเปิดในขั้นตอนถัดไป")}>แก้ไข</button></td></tr>)}</tbody></table></div></>;
}
